import { AuthModule } from '../auth/authentication';
import { type IWalletProviderServiceClient } from './walletProviderServiceClientInterface';
import { KeygenResponse, OperationStatusResponse, RegisterPasskeyResponse, SignResponse } from './types';
/**
 * Type of sign request.
 * @alpha
 */
export type SignRequestType = 'accountAbstractionTx' | 'EIP712' | 'EIP191' | 'rawBytes' | 'eddsa';
/**
 * Builder class for constructing SignRequest instances.
 */
export declare class SignRequestBuilder {
    private signRequest;
    /**
     * Sets the transaction ID, message, and request type for the sign request.
     * Ensures that each transaction ID is only set once.
     * @param transactionId - The transaction ID.
     * @param message - The message to be signed.
     * @param requestType - The type of the sign request.
     * @returns The builder instance.
     */
    setRequest(transactionId: string, message: string, requestType: SignRequestType): SignRequestBuilder;
    /**
     * Builds and returns the SignRequest instance as a Map.
     * @returns The constructed SignRequest instance as a Map.
     */
    build(): string;
}
/** The networkSigner contains an API to communicate with the Silent MPC Network. Call to sign and keygen require
 * the Auth module, that is used to prompt the User before executing the request.
 * @alpha
 */
export declare class NetworkSigner {
    /** Authentication module, used to get confirmation from the User before request execution */
    authModule: AuthModule;
    /** Number of nodes that needs to participate in protocol in order to generate valid signature. Also known as `t`. */
    threshold: number;
    /** Number of nodes that participate in keygen operation. Also known as `n`. */
    totalNodes: number;
    /** Wallet Provider backend client */
    wpClient: IWalletProviderServiceClient;
    /**
     * Facade class used to execute operations on Silent Network.
     * @param wpClient - Wallet Provider backend client
     * @param threshold - Number of nodes that needs to participate in protocol in order to generate valid signature. Also known as `t`.
     * @param totalNodes - Number of nodes that participate in keygen operation. Also known as `n`.
     * @param authModule - Authentication module, used to get confirmation from the User before request execution
     */
    constructor(wpClient: IWalletProviderServiceClient, threshold: number, totalNodes: number, authModule: AuthModule);
    /** Generate a distributed key that's generated by Silent Network.
     * Uses `authModule` to authenticate the User with the Silent Network.
     * @param signAlgs - signature algorithms for which MPC keys will be generated.
     * @param permissions - optional permissions that will be stored in the key metadata.
     * The permissions are validated during sign requests.
     * @returns {@link KeygenResponse} containing `keyId` and the `pubKey` public part of the key
     * @public
     */
    generateKey(signAlgs: string[], permissions?: string): Promise<KeygenResponse[]>;
    /** Generate a signature by the distributed key of Silent Network.
     * Uses `authModule` to authenticate the sign request by the User.
     * The network chooses `t` nodes to execute the protocol.
     * @param keyId - the key id returned from `keygen`
     * @param signAlg - the signature algorithm to use for MPC signing, different form signAlg inside EphKeyClaim
     * @param signRequest - the sign request containing the transaction id, request type and message to sign
     * @returns {@link SignResponse}
     * @public
     */
    signMessage(keyId: string, signAlg: string, signRequest: string): Promise<SignResponse[]>;
    /** Add new ephemeral key to an exist distributed key on the network.
     * Uses `authModule` to authenticate the request by the User.
     * @param keyId - the key id returned from `keygen`
     * @returns {@link OperationStatusResponse}
     * @public
     */
    addEphemeralKey(keyId: string): Promise<OperationStatusResponse>;
    /** Revoke ephemeral key of an exist distributed key on the network.
     * Uses `authModule` to authenticate the request by the User.
     * @param keyId - the key id returned from `keygen`
     * @returns {@link OperationStatusResponse}
     * @public
     */
    revokeEphemeralKey(keyId: string): Promise<OperationStatusResponse>;
    /** Register new user's passkey on the network. This will try to register to all the available nodes on the network.
     * Uses `authModule` to authenticate the request by the User.
     * @returns {@link RegisterPasskeyResponse}
     * @public
     */
    registerPasskey(): Promise<RegisterPasskeyResponse>;
    private setEphClaimOf;
}
/**
 *
 * @param signgenResponse - response from the network for sign request
 * @returns - flattened signature in a form: 0x{signature}{recover_id}
 */
export declare const flattenSignature: (signgenResponse: SignResponse) => `0x${string}`;
