export type { SignResponse, KeygenResponse, OperationStatusResponse, RegisterPasskeyResponse } from './client/types';
export type { SignRequestType } from './client/networkSigner';
export type { ApiVersion, ClientConfig, IWalletProviderServiceClient, } from './client/walletProviderServiceClientInterface';
export type { IBrowserWallet, TypedData } from './auth/EOAauthentication';
export type { PasskeyUser, RelyingPartyConfig } from './auth/passkeyAuthentication';
export type { SignAlgorithm } from './auth/ephemeralAuthentication';
export { NetworkSigner, SignRequestBuilder, flattenSignature } from './client/networkSigner';
export { WalletProviderServiceClient, parseSigngenResult } from './client/walletProviderServiceClient';
export { HttpClient } from './client/api';
export { EOAAuth, EphAuth, PasskeyAuth, PasskeyRegister } from './auth/authentication';
export { generateEphPrivateKey, getEphPublicKey, EphKeyClaim } from './auth/ephemeralAuthentication';
export { computeAddress } from './viemSigner';
import { NetworkSigner, SignRequestBuilder } from './client/networkSigner';
import { WalletProviderServiceClient } from './client/walletProviderServiceClient';
import { HttpClient } from './client/api';
import { EOAAuth, EphAuth, PasskeyAuth, PasskeyRegister } from './auth/authentication';
import { generateEphPrivateKey, getEphPublicKey, EphKeyClaim } from './auth/ephemeralAuthentication';
import { computeAddress } from './viemSigner';
declare const _default: {
    NetworkSigner: typeof NetworkSigner;
    SignRequestBuilder: typeof SignRequestBuilder;
    WalletProviderServiceClient: typeof WalletProviderServiceClient;
    HttpClient: typeof HttpClient;
    EOAAuth: typeof EOAAuth;
    EphAuth: typeof EphAuth;
    PasskeyAuth: typeof PasskeyAuth;
    PasskeyRegister: typeof PasskeyRegister;
    generateEphPrivateKey: typeof generateEphPrivateKey;
    getEphPublicKey: typeof getEphPublicKey;
    EphKeyClaim: typeof EphKeyClaim;
    computeAddress: typeof computeAddress;
    flattenSignature: (signgenResponse: import(".").SignResponse) => `0x${string}`;
    parseSigngenResult: (signResult: string, signAlg: string) => import(".").SignResponse[];
};
export default _default;
